#!/bin/bash

start() {
    rm -rf /home/pi/.cache/mozilla/
    #rm -rf /home/pi/.cache/mozilla/firefox/
    DISPLAY=:0  /usr/bin/firefox-esr -private-window -kiosk https://192.168.0.222/heating.html &
    #sleep 10
    #xdotool search --sync --onlyvisible --name firefox-esr key F11

}

stop() {
	pkill -o firefox-esr
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
