#!/bin/bash

start() {
    rm -rf /home/pi/.cache/mozilla/
    DISPLAY=:0  /usr/bin/firefox http://192.168.0.222 \
        --kiosk &

}

stop() {
	pkill -o firefox-esr
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
