UPLOAD_PORT = /dev/tty.usbserial-A90ZBP5L
#UPLOAD_PORT = /dev/tty.usbserial-14130
UPLOAD_SPEED = 460800
BOARD=nodemcuv2
FS_DIR=data
OTA_ADDR=temp-15348900

include /Users/karotka/Arduino/make.esp/makeEspArduino.mk
