[Default]

[Daemon]
Pid = /var/run/smart.home.daemon/daemon.pid
Interval=15
LogFile = log/daemon_log

[Db]
host = 192.168.0.222
port = 6379

[Influx]
host = 192.168.0.224
port = 8086 
db   = invertor
hpDb = hp

[Web]
Host = 192.168.0.222
Port = 8000
LogFile = log/web_log

[Heating]
roomNames = Obyvák, Kačka, Petr, Koupelna, Ložnice, Vchod, Pracovna, Garáž
roomIds = obyvak, kacka, petr, koupelna, loznice, vchod, pracovna, garaz
minimalTemperature = 7
maximalTemperature = 28
hysteresis = 0.15
hwIp = 192.168.0.6
port = 0
; 192.168.0.20 - sensor1 10200555
; 192.168
[HeatingSensors]
sensorIds = 10178502,  10243897,     10202255,     10246875,     10204017,     10200594,     10178453,     10040010
roomIds =   obyvak,    kacka,        petr,         koupelna,     loznice,      vchod,        pracovna,     garaz
hwIp = 192.168.0.12,   192.168.0.13, 192.168.0.11, 192.168.0.17, 192.168.0.14, 192.168.0.19, 192.168.0.16, 192.168.0.18
; | chodba | kuchyn | obyvak stred | obyvak zadni | koupelna | loznice | garaz | dilna | kacka | petr
mapSensorsToManifold = {10178502:[1,2], 10243897:[7], 10202255:[8], 10246875:[3], 10204017:[4], 10178453:[6], 10040010:[5], 10200594:[0]}
manifoldIp=192.168.0.5

[Lights]
items = {"chodba" : {'ip' : '192.168.0.6', 'name':'Chodba', 'port':1}, "vstup" : {'ip' : '192.168.0.6', 'name':'Vstup', 'port' : 2}, "koupelna" : {'ip' : '192.168.0.6', 'name' : 'Koupelna', 'port' : 3}}
httpConn = 1

[Blinds]
items = {
    "holky_l": {"id": "bfc1fc86c070336c42jwbq", "name": "Žaluzie holky levá",  "ip": "192.168.0.151", "key": "(!|1VVOD5c|;<!w/", "ver": "3.3", "room": "Holky"},
    "holky_p": {"id": "bfb89e90a86ba76e9158bs", "name": "Roleta holky pravá",  "ip": "192.168.1.14",  "key": "QaGv'4-=9K8*aFp_", "ver": "3.3", "room": "Holky"},
    "petr_p":  {"id": "bf3874f416539018e3nwzv", "name": "Roleta Petr pravá",   "ip": "192.168.0.4",   "key": "3^~SFwcpcFC_P}0_", "ver": "3.3", "room": "Petr"},
    "petr_l":  {"id": "bf664fd116ed403dc6k1tk", "name": "Roleta Petr levá",    "ip": "192.168.0.190", "key": "1OsD70n>27h]^RHn", "ver": "3.3", "room": "Petr"},
    "terasa":  {"id": "bf9a362c8c6c46ae9aotgd", "name": "Roleta terasa",       "ip": "192.168.1.55",  "key": "(D@i>w7uNT:[.S:$", "ver": "3.3", "room": "Terasa"},
    "jidelni": {"id": "bf5a88a6a9bf0bdd33saat", "name": "Roleta jídelní stůl", "ip": "192.168.0.171", "key": "N61aShqw<iGlv;h(", "ver": "3.3", "room": "Jídelna"}
    }


