#!/bin/bash

rm -rf /home/pi/.cache/chromium/
DISPLAY=:0  /usr/bin/chromium-browser --app=http://localhost:8000 \
	--kiosk \
	--noerrdialogs \
	--disable-session-crashed-bubble \
	--disable-infobars \
	--disable-pinch	
